/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20ForSplSol from './erc20_for_spl.sol/index.js';
export * as erc20ForSplFactorySol from './erc20_for_spl_factory.sol/index.js';
export * as v1 from './v1/index.js';