/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CallAssociatedTokenProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CallAssociatedTokenProgram__factory>
getContractFactory(name: 'CallMetaplexProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CallMetaplexProgram__factory>
getContractFactory(name: 'CallRaydiumProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CallRaydiumProgram__factory>
getContractFactory(name: 'IERC20ForSpl', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20ForSpl__factory>
getContractFactory(name: 'CallSPLTokenProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CallSPLTokenProgram__factory>
getContractFactory(name: 'CallSystemProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CallSystemProgram__factory>
getContractFactory(name: 'Constants', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Constants__factory>
getContractFactory(name: 'LibAssociatedTokenData', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibAssociatedTokenData__factory>
getContractFactory(name: 'LibMetaplexData', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibMetaplexData__factory>
getContractFactory(name: 'LibMetaplexErrors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibMetaplexErrors__factory>
getContractFactory(name: 'LibMetaplexProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibMetaplexProgram__factory>
getContractFactory(name: 'LibRaydiumData', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibRaydiumData__factory>
getContractFactory(name: 'LibRaydiumErrors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibRaydiumErrors__factory>
getContractFactory(name: 'LibRaydiumProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibRaydiumProgram__factory>
getContractFactory(name: 'LibSPLTokenData', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibSPLTokenData__factory>
getContractFactory(name: 'LibSPLTokenErrors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibSPLTokenErrors__factory>
getContractFactory(name: 'LibSystemData', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibSystemData__factory>
getContractFactory(name: 'LibSystemErrors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibSystemErrors__factory>
getContractFactory(name: 'MockCallSystemProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockCallSystemProgram__factory>
getContractFactory(name: 'IERC20ForSPL', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20ForSPL__factory>
getContractFactory(name: 'MockVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockVault__factory>
getContractFactory(name: 'PythAggregatorV3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PythAggregatorV3__factory>
getContractFactory(name: 'SolanaVRF', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SolanaVRF__factory>
getContractFactory(name: 'ICallSolana', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICallSolana__factory>
getContractFactory(name: 'IMetaplexProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMetaplexProgram__factory>
getContractFactory(name: 'INeonWithdraw', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INeonWithdraw__factory>
getContractFactory(name: 'ISPLTokenProgram', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISPLTokenProgram__factory>
getContractFactory(name: 'ISolanaNative', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISolanaNative__factory>
getContractFactory(name: 'ERC20ForSpl', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20ForSpl__factory>
getContractFactory(name: 'ERC20ForSplBackbone', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20ForSplBackbone__factory>
getContractFactory(name: 'ERC20ForSplMintable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20ForSplMintable__factory>
getContractFactory(name: 'ERC20ForSplFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20ForSplFactory__factory>
getContractFactory(name: 'Metaplex', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Metaplex__factory>
getContractFactory(name: 'SPLToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SPLToken__factory>
getContractFactory(name: 'ERC20ForSpl', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20ForSpl__factory>
getContractFactory(name: 'ERC20ForSplMintable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20ForSplMintable__factory>
getContractFactory(name: 'ERC20ForSplFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20ForSplFactory__factory>
getContractFactory(name: 'CallSolanaValidationLib', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CallSolanaValidationLib__factory>

  getContractAt(name: 'CallAssociatedTokenProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CallAssociatedTokenProgram>
getContractAt(name: 'CallMetaplexProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CallMetaplexProgram>
getContractAt(name: 'CallRaydiumProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CallRaydiumProgram>
getContractAt(name: 'IERC20ForSpl', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20ForSpl>
getContractAt(name: 'CallSPLTokenProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CallSPLTokenProgram>
getContractAt(name: 'CallSystemProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CallSystemProgram>
getContractAt(name: 'Constants', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Constants>
getContractAt(name: 'LibAssociatedTokenData', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibAssociatedTokenData>
getContractAt(name: 'LibMetaplexData', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibMetaplexData>
getContractAt(name: 'LibMetaplexErrors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibMetaplexErrors>
getContractAt(name: 'LibMetaplexProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibMetaplexProgram>
getContractAt(name: 'LibRaydiumData', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibRaydiumData>
getContractAt(name: 'LibRaydiumErrors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibRaydiumErrors>
getContractAt(name: 'LibRaydiumProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibRaydiumProgram>
getContractAt(name: 'LibSPLTokenData', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibSPLTokenData>
getContractAt(name: 'LibSPLTokenErrors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibSPLTokenErrors>
getContractAt(name: 'LibSystemData', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibSystemData>
getContractAt(name: 'LibSystemErrors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibSystemErrors>
getContractAt(name: 'MockCallSystemProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockCallSystemProgram>
getContractAt(name: 'IERC20ForSPL', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20ForSPL>
getContractAt(name: 'MockVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockVault>
getContractAt(name: 'PythAggregatorV3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PythAggregatorV3>
getContractAt(name: 'SolanaVRF', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SolanaVRF>
getContractAt(name: 'ICallSolana', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICallSolana>
getContractAt(name: 'IMetaplexProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMetaplexProgram>
getContractAt(name: 'INeonWithdraw', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INeonWithdraw>
getContractAt(name: 'ISPLTokenProgram', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISPLTokenProgram>
getContractAt(name: 'ISolanaNative', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISolanaNative>
getContractAt(name: 'ERC20ForSpl', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20ForSpl>
getContractAt(name: 'ERC20ForSplBackbone', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20ForSplBackbone>
getContractAt(name: 'ERC20ForSplMintable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20ForSplMintable>
getContractAt(name: 'ERC20ForSplFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20ForSplFactory>
getContractAt(name: 'Metaplex', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Metaplex>
getContractAt(name: 'SPLToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SPLToken>
getContractAt(name: 'ERC20ForSpl', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20ForSpl>
getContractAt(name: 'ERC20ForSplMintable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20ForSplMintable>
getContractAt(name: 'ERC20ForSplFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20ForSplFactory>
getContractAt(name: 'CallSolanaValidationLib', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CallSolanaValidationLib>

  deployContract(name: 'CallAssociatedTokenProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallAssociatedTokenProgram>
deployContract(name: 'CallMetaplexProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallMetaplexProgram>
deployContract(name: 'CallRaydiumProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallRaydiumProgram>
deployContract(name: 'IERC20ForSpl', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20ForSpl>
deployContract(name: 'CallSPLTokenProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallSPLTokenProgram>
deployContract(name: 'CallSystemProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallSystemProgram>
deployContract(name: 'Constants', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Constants>
deployContract(name: 'LibAssociatedTokenData', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibAssociatedTokenData>
deployContract(name: 'LibMetaplexData', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibMetaplexData>
deployContract(name: 'LibMetaplexErrors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibMetaplexErrors>
deployContract(name: 'LibMetaplexProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibMetaplexProgram>
deployContract(name: 'LibRaydiumData', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibRaydiumData>
deployContract(name: 'LibRaydiumErrors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibRaydiumErrors>
deployContract(name: 'LibRaydiumProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibRaydiumProgram>
deployContract(name: 'LibSPLTokenData', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSPLTokenData>
deployContract(name: 'LibSPLTokenErrors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSPLTokenErrors>
deployContract(name: 'LibSystemData', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSystemData>
deployContract(name: 'LibSystemErrors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSystemErrors>
deployContract(name: 'MockCallSystemProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockCallSystemProgram>
deployContract(name: 'IERC20ForSPL', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20ForSPL>
deployContract(name: 'MockVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockVault>
deployContract(name: 'PythAggregatorV3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PythAggregatorV3>
deployContract(name: 'SolanaVRF', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SolanaVRF>
deployContract(name: 'ICallSolana', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICallSolana>
deployContract(name: 'IMetaplexProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMetaplexProgram>
deployContract(name: 'INeonWithdraw', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INeonWithdraw>
deployContract(name: 'ISPLTokenProgram', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISPLTokenProgram>
deployContract(name: 'ISolanaNative', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISolanaNative>
deployContract(name: 'ERC20ForSpl', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSpl>
deployContract(name: 'ERC20ForSplBackbone', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplBackbone>
deployContract(name: 'ERC20ForSplMintable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplMintable>
deployContract(name: 'ERC20ForSplFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplFactory>
deployContract(name: 'Metaplex', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Metaplex>
deployContract(name: 'SPLToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SPLToken>
deployContract(name: 'ERC20ForSpl', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSpl>
deployContract(name: 'ERC20ForSplMintable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplMintable>
deployContract(name: 'ERC20ForSplFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplFactory>
deployContract(name: 'CallSolanaValidationLib', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallSolanaValidationLib>

  deployContract(name: 'CallAssociatedTokenProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallAssociatedTokenProgram>
deployContract(name: 'CallMetaplexProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallMetaplexProgram>
deployContract(name: 'CallRaydiumProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallRaydiumProgram>
deployContract(name: 'IERC20ForSpl', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20ForSpl>
deployContract(name: 'CallSPLTokenProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallSPLTokenProgram>
deployContract(name: 'CallSystemProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallSystemProgram>
deployContract(name: 'Constants', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Constants>
deployContract(name: 'LibAssociatedTokenData', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibAssociatedTokenData>
deployContract(name: 'LibMetaplexData', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibMetaplexData>
deployContract(name: 'LibMetaplexErrors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibMetaplexErrors>
deployContract(name: 'LibMetaplexProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibMetaplexProgram>
deployContract(name: 'LibRaydiumData', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibRaydiumData>
deployContract(name: 'LibRaydiumErrors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibRaydiumErrors>
deployContract(name: 'LibRaydiumProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibRaydiumProgram>
deployContract(name: 'LibSPLTokenData', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSPLTokenData>
deployContract(name: 'LibSPLTokenErrors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSPLTokenErrors>
deployContract(name: 'LibSystemData', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSystemData>
deployContract(name: 'LibSystemErrors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibSystemErrors>
deployContract(name: 'MockCallSystemProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockCallSystemProgram>
deployContract(name: 'IERC20ForSPL', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20ForSPL>
deployContract(name: 'MockVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockVault>
deployContract(name: 'PythAggregatorV3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PythAggregatorV3>
deployContract(name: 'SolanaVRF', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SolanaVRF>
deployContract(name: 'ICallSolana', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICallSolana>
deployContract(name: 'IMetaplexProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMetaplexProgram>
deployContract(name: 'INeonWithdraw', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INeonWithdraw>
deployContract(name: 'ISPLTokenProgram', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISPLTokenProgram>
deployContract(name: 'ISolanaNative', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISolanaNative>
deployContract(name: 'ERC20ForSpl', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSpl>
deployContract(name: 'ERC20ForSplBackbone', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplBackbone>
deployContract(name: 'ERC20ForSplMintable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplMintable>
deployContract(name: 'ERC20ForSplFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplFactory>
deployContract(name: 'Metaplex', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Metaplex>
deployContract(name: 'SPLToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SPLToken>
deployContract(name: 'ERC20ForSpl', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSpl>
deployContract(name: 'ERC20ForSplMintable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplMintable>
deployContract(name: 'ERC20ForSplFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20ForSplFactory>
deployContract(name: 'CallSolanaValidationLib', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CallSolanaValidationLib>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  