/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IERC20ForSpl, IERC20ForSplInterface } from "../../../composability/CallRaydiumProgram.sol/IERC20ForSpl.js";

  const _abi = [
  {
    "inputs": [],
    "name": "tokenMint",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transferFrom",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "to",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      }
    ],
    "name": "transferSolana",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IERC20ForSpl__factory {
    static readonly abi = _abi;
    static createInterface(): IERC20ForSplInterface {
      return new Interface(_abi) as IERC20ForSplInterface;
    }
    
    override attach(address: string | Addressable): IERC20ForSpl {
      return super.attach(address) as IERC20ForSpl;
    }
  static connect(address: string, runner?: ContractRunner | null): IERC20ForSpl {
      return new Contract(address, _abi, runner) as unknown as IERC20ForSpl;
    }
  }
  