/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace LibSPLTokenData {
      
    export type SPLTokenAccountDataStruct = {mint: BytesLike, owner: BytesLike, balance: BigNumberish, delegateOption: BytesLike, delegate: BytesLike, isInitialized: boolean, isNativeOption: BytesLike, isNative: boolean, delegatedAmount: BigNumberish, closeAuthorityOption: BytesLike, closeAuthority: BytesLike}

    export type SPLTokenAccountDataStructOutput = [mint: string, owner: string, balance: bigint, delegateOption: string, delegate: string, isInitialized: boolean, isNativeOption: string, isNative: boolean, delegatedAmount: bigint, closeAuthorityOption: string, closeAuthority: string] & {mint: string, owner: string, balance: bigint, delegateOption: string, delegate: string, isInitialized: boolean, isNativeOption: string, isNative: boolean, delegatedAmount: bigint, closeAuthorityOption: string, closeAuthority: string }
  

    export type SPLTokenMintDataStruct = {mintAuthorityOption: BytesLike, mintAuthority: BytesLike, supply: BigNumberish, decimals: BigNumberish, isInitialized: boolean, freezeAuthorityOption: BytesLike, freezeAuthority: BytesLike}

    export type SPLTokenMintDataStructOutput = [mintAuthorityOption: string, mintAuthority: string, supply: bigint, decimals: bigint, isInitialized: boolean, freezeAuthorityOption: string, freezeAuthority: string] & {mintAuthorityOption: string, mintAuthority: string, supply: bigint, decimals: bigint, isInitialized: boolean, freezeAuthorityOption: string, freezeAuthority: string }
  
    }

export declare namespace LibMetaplexData {
      
    export type TokenMetadataStruct = {tokenName: string, tokenSymbol: string, uri: string, isMutable: boolean, updateAuthority: BytesLike}

    export type TokenMetadataStructOutput = [tokenName: string, tokenSymbol: string, uri: string, isMutable: boolean, updateAuthority: string] & {tokenName: string, tokenSymbol: string, uri: string, isMutable: boolean, updateAuthority: string }
  
    }

  export interface CallSPLTokenProgramInterface extends Interface {
    getFunction(nameOrSignature: "CALL_SOLANA" | "approve" | "burn" | "claim" | "closeTokenAccount" | "createInitializeArbitraryTokenAccount" | "createInitializeTokenMint" | "createTokenMetadataAccount" | "getArbitraryTokenAccount" | "getAssociatedTokenAccount" | "getMetadataIsMutable" | "getMetadataPDA" | "getMetadataUpdateAuthority" | "getMetaplexCreateFee" | "getNeonAddress" | "getSPLTokenAccountBalance" | "getSPLTokenAccountCloseAuthority" | "getSPLTokenAccountData" | "getSPLTokenAccountDelegate" | "getSPLTokenAccountDelegatedAmount" | "getSPLTokenAccountIsInitialized" | "getSPLTokenAccountIsNative" | "getSPLTokenAccountMint" | "getSPLTokenAccountOwner" | "getSPLTokenDecimals" | "getSPLTokenFreezeAuthority" | "getSPLTokenMintAuthority" | "getSPLTokenMintData" | "getSPLTokenMintIsInitialized" | "getSPLTokenSupply" | "getTokenMetadata" | "getTokenMintAccount" | "getTokenName" | "getTokenSymbol" | "getUri" | "mint" | "revokeApproval" | "syncWrappedSOLAccount" | "transfer" | "updateTokenAccountAuthority" | "updateTokenMetadataAccount" | "updateTokenMintAuthority"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'CALL_SOLANA', values?: undefined): string;
encodeFunctionData(functionFragment: 'approve', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'burn', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claim', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeTokenAccount', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createInitializeArbitraryTokenAccount', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createInitializeTokenMint', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTokenMetadataAccount', values: [BytesLike, string, string, string, boolean]): string;
encodeFunctionData(functionFragment: 'getArbitraryTokenAccount', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAssociatedTokenAccount', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getMetadataIsMutable', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMetadataPDA', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMetadataUpdateAuthority', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMetaplexCreateFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getNeonAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountBalance', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountCloseAuthority', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountData', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountDelegate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountDelegatedAmount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountIsInitialized', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountIsNative', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountMint', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenAccountOwner', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenDecimals', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenFreezeAuthority', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenMintAuthority', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenMintData', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenMintIsInitialized', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSPLTokenSupply', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenMetadata', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenMintAccount', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenName', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenSymbol', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getUri', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeApproval', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'syncWrappedSOLAccount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transfer', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateTokenAccountAuthority', values: [BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'updateTokenMetadataAccount', values: [BytesLike, string, string, string, BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'updateTokenMintAuthority', values: [BytesLike, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'CALL_SOLANA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeTokenAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createInitializeArbitraryTokenAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createInitializeTokenMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTokenMetadataAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArbitraryTokenAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssociatedTokenAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadataIsMutable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadataPDA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadataUpdateAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetaplexCreateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNeonAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountCloseAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountDelegate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountDelegatedAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountIsInitialized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountIsNative', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenAccountOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenDecimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenFreezeAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenMintAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenMintData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenMintIsInitialized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSPLTokenSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenMintAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenSymbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeApproval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'syncWrappedSOLAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenAccountAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenMetadataAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenMintAuthority', data: BytesLike): Result;
  }

  

  export interface CallSPLTokenProgram extends BaseContract {
    
    connect(runner?: ContractRunner | null): CallSPLTokenProgram;
    waitForDeployment(): Promise<this>;

    interface: CallSPLTokenProgramInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CALL_SOLANA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [tokenMint: BytesLike, delegate: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burn: TypedContractMethod<
      [tokenMint: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claim: TypedContractMethod<
      [senderATA: BytesLike, recipientATA: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closeTokenAccount: TypedContractMethod<
      [tokenMint: BytesLike, destination: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createInitializeArbitraryTokenAccount: TypedContractMethod<
      [tokenMint: BytesLike, owner: BytesLike, tokenOwner: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createInitializeTokenMint: TypedContractMethod<
      [seed: BytesLike, decimals: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createTokenMetadataAccount: TypedContractMethod<
      [seed: BytesLike, tokenName: string, tokenSymbol: string, tokenUri: string, isMutable: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    getArbitraryTokenAccount: TypedContractMethod<
      [tokenMint: BytesLike, ownerPubKey: BytesLike, nonce: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getAssociatedTokenAccount: TypedContractMethod<
      [tokenMint: BytesLike, ownerPubKey: BytesLike, ],
      [string],
      'view'
    >
    

    
    getMetadataIsMutable: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getMetadataPDA: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getMetadataUpdateAuthority: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getMetaplexCreateFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getNeonAddress: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getSPLTokenAccountBalance: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getSPLTokenAccountCloseAuthority: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSPLTokenAccountData: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [LibSPLTokenData.SPLTokenAccountDataStructOutput],
      'view'
    >
    

    
    getSPLTokenAccountDelegate: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSPLTokenAccountDelegatedAmount: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getSPLTokenAccountIsInitialized: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getSPLTokenAccountIsNative: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getSPLTokenAccountMint: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSPLTokenAccountOwner: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSPLTokenDecimals: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getSPLTokenFreezeAuthority: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSPLTokenMintAuthority: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSPLTokenMintData: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [LibSPLTokenData.SPLTokenMintDataStructOutput],
      'view'
    >
    

    
    getSPLTokenMintIsInitialized: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getSPLTokenSupply: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getTokenMetadata: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [LibMetaplexData.TokenMetadataStructOutput],
      'view'
    >
    

    
    getTokenMintAccount: TypedContractMethod<
      [owner: AddressLike, seed: BytesLike, ],
      [string],
      'view'
    >
    

    
    getTokenName: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getTokenSymbol: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getUri: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [seed: BytesLike, recipientATA: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeApproval: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    syncWrappedSOLAccount: TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    transfer: TypedContractMethod<
      [tokenMint: BytesLike, recipientATA: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokenAccountAuthority: TypedContractMethod<
      [tokenMint: BytesLike, authorityType: BigNumberish, newAuthority: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokenMetadataAccount: TypedContractMethod<
      [seed: BytesLike, newTokenName: string, newTokenSymbol: string, newTokenUri: string, newUpdateAuthority: BytesLike, isMutable: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokenMintAuthority: TypedContractMethod<
      [seed: BytesLike, authorityType: BigNumberish, newAuthority: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CALL_SOLANA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [tokenMint: BytesLike, delegate: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [tokenMint: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [senderATA: BytesLike, recipientATA: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeTokenAccount'): TypedContractMethod<
      [tokenMint: BytesLike, destination: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createInitializeArbitraryTokenAccount'): TypedContractMethod<
      [tokenMint: BytesLike, owner: BytesLike, tokenOwner: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createInitializeTokenMint'): TypedContractMethod<
      [seed: BytesLike, decimals: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTokenMetadataAccount'): TypedContractMethod<
      [seed: BytesLike, tokenName: string, tokenSymbol: string, tokenUri: string, isMutable: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getArbitraryTokenAccount'): TypedContractMethod<
      [tokenMint: BytesLike, ownerPubKey: BytesLike, nonce: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAssociatedTokenAccount'): TypedContractMethod<
      [tokenMint: BytesLike, ownerPubKey: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMetadataIsMutable'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getMetadataPDA'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMetadataUpdateAuthority'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMetaplexCreateFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getNeonAddress'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountBalance'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountCloseAuthority'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountData'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [LibSPLTokenData.SPLTokenAccountDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountDelegate'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountDelegatedAmount'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountIsInitialized'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountIsNative'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountMint'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenAccountOwner'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenDecimals'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenFreezeAuthority'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenMintAuthority'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenMintData'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [LibSPLTokenData.SPLTokenMintDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenMintIsInitialized'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getSPLTokenSupply'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenMetadata'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [LibMetaplexData.TokenMetadataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenMintAccount'): TypedContractMethod<
      [owner: AddressLike, seed: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenName'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenSymbol'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUri'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [seed: BytesLike, recipientATA: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeApproval'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'syncWrappedSOLAccount'): TypedContractMethod<
      [tokenAccount: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [tokenMint: BytesLike, recipientATA: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenAccountAuthority'): TypedContractMethod<
      [tokenMint: BytesLike, authorityType: BigNumberish, newAuthority: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenMetadataAccount'): TypedContractMethod<
      [seed: BytesLike, newTokenName: string, newTokenSymbol: string, newTokenUri: string, newUpdateAuthority: BytesLike, isMutable: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenMintAuthority'): TypedContractMethod<
      [seed: BytesLike, authorityType: BigNumberish, newAuthority: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }