/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace LibMetaplexData {
      
    export type TokenMetadataStruct = {tokenName: string, tokenSymbol: string, uri: string, isMutable: boolean, updateAuthority: BytesLike}

    export type TokenMetadataStructOutput = [tokenName: string, tokenSymbol: string, uri: string, isMutable: boolean, updateAuthority: string] & {tokenName: string, tokenSymbol: string, uri: string, isMutable: boolean, updateAuthority: string }
  
    }

  export interface CallMetaplexProgramInterface extends Interface {
    getFunction(nameOrSignature: "CALL_SOLANA" | "createTokenMetadataAccount" | "getMetadataIsMutable" | "getMetadataPDA" | "getMetadataUpdateAuthority" | "getMetaplexCreateFee" | "getNeonAddress" | "getTokenMetadata" | "getTokenMintAccount" | "getTokenName" | "getTokenSymbol" | "getUri" | "updateTokenMetadataAccount"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'CALL_SOLANA', values?: undefined): string;
encodeFunctionData(functionFragment: 'createTokenMetadataAccount', values: [BytesLike, string, string, string, boolean]): string;
encodeFunctionData(functionFragment: 'getMetadataIsMutable', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMetadataPDA', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMetadataUpdateAuthority', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMetaplexCreateFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getNeonAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokenMetadata', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenMintAccount', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenName', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenSymbol', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getUri', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateTokenMetadataAccount', values: [BytesLike, string, string, string, BytesLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'CALL_SOLANA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTokenMetadataAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadataIsMutable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadataPDA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetadataUpdateAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMetaplexCreateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNeonAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenMintAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenSymbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenMetadataAccount', data: BytesLike): Result;
  }

  

  export interface CallMetaplexProgram extends BaseContract {
    
    connect(runner?: ContractRunner | null): CallMetaplexProgram;
    waitForDeployment(): Promise<this>;

    interface: CallMetaplexProgramInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CALL_SOLANA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createTokenMetadataAccount: TypedContractMethod<
      [seed: BytesLike, tokenName: string, tokenSymbol: string, tokenUri: string, isMutable: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    getMetadataIsMutable: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getMetadataPDA: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getMetadataUpdateAuthority: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getMetaplexCreateFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getNeonAddress: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getTokenMetadata: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [LibMetaplexData.TokenMetadataStructOutput],
      'view'
    >
    

    
    getTokenMintAccount: TypedContractMethod<
      [owner: AddressLike, seed: BytesLike, ],
      [string],
      'view'
    >
    

    
    getTokenName: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getTokenSymbol: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    getUri: TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >
    

    
    updateTokenMetadataAccount: TypedContractMethod<
      [seed: BytesLike, newTokenName: string, newTokenSymbol: string, newTokenUri: string, newUpdateAuthority: BytesLike, isMutable: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CALL_SOLANA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createTokenMetadataAccount'): TypedContractMethod<
      [seed: BytesLike, tokenName: string, tokenSymbol: string, tokenUri: string, isMutable: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMetadataIsMutable'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getMetadataPDA'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMetadataUpdateAuthority'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMetaplexCreateFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getNeonAddress'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenMetadata'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [LibMetaplexData.TokenMetadataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenMintAccount'): TypedContractMethod<
      [owner: AddressLike, seed: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenName'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenSymbol'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUri'): TypedContractMethod<
      [tokenMint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateTokenMetadataAccount'): TypedContractMethod<
      [seed: BytesLike, newTokenName: string, newTokenSymbol: string, newTokenUri: string, newUpdateAuthority: BytesLike, isMutable: boolean, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }