/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CallSystemProgramInterface extends Interface {
    getFunction(nameOrSignature: "CALL_SOLANA" | "allocate" | "assign" | "createAccountWithSeed" | "getBalance" | "getCreateWithSeedAccount" | "getIsExecutable" | "getNeonAddress" | "getOwner" | "getRentEpoch" | "getRentExemptionBalance" | "getSpace" | "getSystemAccountData" | "isRentExempt" | "transfer"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'CALL_SOLANA', values?: undefined): string;
encodeFunctionData(functionFragment: 'allocate', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'assign', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createAccountWithSeed', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBalance', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getCreateWithSeedAccount', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getIsExecutable', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getNeonAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getOwner', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRentEpoch', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRentExemptionBalance', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSpace', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSystemAccountData', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isRentExempt', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transfer', values: [BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'CALL_SOLANA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allocate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAccountWithSeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreateWithSeedAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getIsExecutable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNeonAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRentEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRentExemptionBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSpace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSystemAccountData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRentExempt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
  }

  

  export interface CallSystemProgram extends BaseContract {
    
    connect(runner?: ContractRunner | null): CallSystemProgram;
    waitForDeployment(): Promise<this>;

    interface: CallSystemProgramInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CALL_SOLANA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allocate: TypedContractMethod<
      [programId: BytesLike, seed: BytesLike, accountSize: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    assign: TypedContractMethod<
      [programId: BytesLike, seed: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createAccountWithSeed: TypedContractMethod<
      [programId: BytesLike, seed: BytesLike, accountSize: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBalance: TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getCreateWithSeedAccount: TypedContractMethod<
      [basePubKey: BytesLike, programId: BytesLike, seed: BytesLike, ],
      [string],
      'view'
    >
    

    
    getIsExecutable: TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getNeonAddress: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getOwner: TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [string],
      'view'
    >
    

    
    getRentEpoch: TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getRentExemptionBalance: TypedContractMethod<
      [accountBytesSize: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getSpace: TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getSystemAccountData: TypedContractMethod<
      [accountPubKey: BytesLike, size: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isRentExempt: TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [recipient: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CALL_SOLANA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allocate'): TypedContractMethod<
      [programId: BytesLike, seed: BytesLike, accountSize: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assign'): TypedContractMethod<
      [programId: BytesLike, seed: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createAccountWithSeed'): TypedContractMethod<
      [programId: BytesLike, seed: BytesLike, accountSize: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCreateWithSeedAccount'): TypedContractMethod<
      [basePubKey: BytesLike, programId: BytesLike, seed: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getIsExecutable'): TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getNeonAddress'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRentEpoch'): TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRentExemptionBalance'): TypedContractMethod<
      [accountBytesSize: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSpace'): TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSystemAccountData'): TypedContractMethod<
      [accountPubKey: BytesLike, size: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isRentExempt'): TypedContractMethod<
      [accountPubKey: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [recipient: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }