/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface ERC20ForSplMintableInterface extends Interface {
    getFunction(nameOrSignature: "ASSOCIATED_TOKEN_PROGRAM_ID" | "CALL_SOLANA" | "METAPLEX_PROGRAM" | "SOLANA_NATIVE" | "SPLTOKEN_PROGRAM" | "TOKEN_PROGRAM_ID" | "acceptOwnership" | "allowance" | "approve" | "approveSolana" | "balanceOf" | "balanceOfATA" | "balanceOfPDA" | "burn" | "burnFrom" | "claim" | "claimTo" | "decimals" | "findMintAccount" | "getAccountDelegateData" | "getTokenMintATA" | "mint" | "name" | "owner" | "pendingOwner" | "renounceOwnership" | "solanaAccount" | "symbol" | "tokenMint" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "transferSolana" | "transferSolanaFrom"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalSolana" | "OwnershipTransferStarted" | "OwnershipTransferred" | "Transfer" | "TransferSolana"): EventFragment;

    encodeFunctionData(functionFragment: 'ASSOCIATED_TOKEN_PROGRAM_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'CALL_SOLANA', values?: undefined): string;
encodeFunctionData(functionFragment: 'METAPLEX_PROGRAM', values?: undefined): string;
encodeFunctionData(functionFragment: 'SOLANA_NATIVE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SPLTOKEN_PROGRAM', values?: undefined): string;
encodeFunctionData(functionFragment: 'TOKEN_PROGRAM_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveSolana', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'balanceOfATA', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'balanceOfPDA', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'burn', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'burnFrom', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claim', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimTo', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'findMintAccount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAccountDelegateData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokenMintATA', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'solanaAccount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenMint', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferSolana', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferSolanaFrom', values: [AddressLike, BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ASSOCIATED_TOKEN_PROGRAM_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CALL_SOLANA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'METAPLEX_PROGRAM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SOLANA_NATIVE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SPLTOKEN_PROGRAM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TOKEN_PROGRAM_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveSolana', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfATA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfPDA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'findMintAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccountDelegateData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenMintATA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'solanaAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferSolana', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferSolanaFrom', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, amount: bigint];
      export interface OutputObject {owner: string, spender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalSolanaEvent {
      export type InputTuple = [owner: AddressLike, spender: BytesLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, amount: bigint];
      export interface OutputObject {owner: string, spender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, to: string, amount: bigint];
      export interface OutputObject {from: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSolanaEvent {
      export type InputTuple = [from: AddressLike, to: BytesLike, amount: BigNumberish];
      export type OutputTuple = [from: string, to: string, amount: bigint];
      export interface OutputObject {from: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ERC20ForSplMintable extends BaseContract {
    
    connect(runner?: ContractRunner | null): ERC20ForSplMintable;
    waitForDeployment(): Promise<this>;

    interface: ERC20ForSplMintableInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ASSOCIATED_TOKEN_PROGRAM_ID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CALL_SOLANA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    METAPLEX_PROGRAM: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SOLANA_NATIVE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SPLTOKEN_PROGRAM: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    TOKEN_PROGRAM_ID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    approveSolana: TypedContractMethod<
      [spender: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    balanceOfATA: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    balanceOfPDA: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    burn: TypedContractMethod<
      [amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    burnFrom: TypedContractMethod<
      [from: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    claim: TypedContractMethod<
      [from: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    claimTo: TypedContractMethod<
      [from: BytesLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    findMintAccount: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAccountDelegateData: TypedContractMethod<
      [account: AddressLike, ],
      [[string, bigint]],
      'view'
    >
    

    
    getTokenMintATA: TypedContractMethod<
      [account: BytesLike, ],
      [string],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    solanaAccount: TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenMint: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferSolana: TypedContractMethod<
      [to: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferSolanaFrom: TypedContractMethod<
      [from: AddressLike, to: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ASSOCIATED_TOKEN_PROGRAM_ID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CALL_SOLANA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'METAPLEX_PROGRAM'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SOLANA_NATIVE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SPLTOKEN_PROGRAM'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'TOKEN_PROGRAM_ID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveSolana'): TypedContractMethod<
      [spender: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfATA'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfPDA'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnFrom'): TypedContractMethod<
      [from: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [from: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTo'): TypedContractMethod<
      [from: BytesLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'findMintAccount'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAccountDelegateData'): TypedContractMethod<
      [account: AddressLike, ],
      [[string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenMintATA'): TypedContractMethod<
      [account: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'solanaAccount'): TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenMint'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferSolana'): TypedContractMethod<
      [to: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferSolanaFrom'): TypedContractMethod<
      [from: AddressLike, to: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalSolana'): TypedContractEvent<ApprovalSolanaEvent.InputTuple, ApprovalSolanaEvent.OutputTuple, ApprovalSolanaEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TransferSolana'): TypedContractEvent<TransferSolanaEvent.InputTuple, TransferSolanaEvent.OutputTuple, TransferSolanaEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalSolana(address,bytes32,uint64)': TypedContractEvent<ApprovalSolanaEvent.InputTuple, ApprovalSolanaEvent.OutputTuple, ApprovalSolanaEvent.OutputObject>;
      ApprovalSolana: TypedContractEvent<ApprovalSolanaEvent.InputTuple, ApprovalSolanaEvent.OutputTuple, ApprovalSolanaEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TransferSolana(address,bytes32,uint64)': TypedContractEvent<TransferSolanaEvent.InputTuple, TransferSolanaEvent.OutputTuple, TransferSolanaEvent.OutputObject>;
      TransferSolana: TypedContractEvent<TransferSolanaEvent.InputTuple, TransferSolanaEvent.OutputTuple, TransferSolanaEvent.OutputObject>;
    
    };
  }