/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20ForSpl } from './ERC20ForSpl.js';
export type { ERC20ForSplBackbone } from './ERC20ForSplBackbone.js';
export type { ERC20ForSplMintable } from './ERC20ForSplMintable.js';