/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace LibRaydiumData {
      
    export type ConfigDataStruct = {disableCreatePool: boolean, index: BigNumberish, tradeFeeRate: BigNumberish, protocolFeeRate: BigNumberish, fundFeeRate: BigNumberish, createPoolFee: BigNumberish, protocolOwner: BytesLike, fundOwner: BytesLike}

    export type ConfigDataStructOutput = [disableCreatePool: boolean, index: bigint, tradeFeeRate: bigint, protocolFeeRate: bigint, fundFeeRate: bigint, createPoolFee: bigint, protocolOwner: string, fundOwner: string] & {disableCreatePool: boolean, index: bigint, tradeFeeRate: bigint, protocolFeeRate: bigint, fundFeeRate: bigint, createPoolFee: bigint, protocolOwner: string, fundOwner: string }
  

    export type PoolDataStruct = {ammConfig: BytesLike, poolCreator: BytesLike, tokenAVault: BytesLike, tokenBVault: BytesLike, lpMint: BytesLike, tokenA: BytesLike, tokenB: BytesLike, tokenAProgram: BytesLike, tokenBProgram: BytesLike, observationKey: BytesLike}

    export type PoolDataStructOutput = [ammConfig: string, poolCreator: string, tokenAVault: string, tokenBVault: string, lpMint: string, tokenA: string, tokenB: string, tokenAProgram: string, tokenBProgram: string, observationKey: string] & {ammConfig: string, poolCreator: string, tokenAVault: string, tokenBVault: string, lpMint: string, tokenA: string, tokenB: string, tokenAProgram: string, tokenBProgram: string, observationKey: string }
  
    }

  export interface CallRaydiumProgramInterface extends Interface {
    getFunction(nameOrSignature: "CALL_SOLANA" | "addLiquidity" | "collectFees" | "createPool" | "createPoolAndLockLP" | "getConfigAccount" | "getConfigData" | "getCpmmPdaPoolId" | "getExtAuthority" | "getNeonAddress" | "getNeonArbitraryTokenAccount" | "getPayer" | "getPdaLpMint" | "getPoolData" | "getPoolLpAmount" | "getSwapInput" | "getSwapOutput" | "getTokenReserve" | "lockLiquidity" | "lpToAmount" | "swapInput" | "swapOutput" | "withdrawLiquidity"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'CALL_SOLANA', values?: undefined): string;
encodeFunctionData(functionFragment: 'addLiquidity', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'collectFees', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'createPool', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createPoolAndLockLP', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'getConfigAccount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getConfigData', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCpmmPdaPoolId', values: [BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getExtAuthority', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getNeonAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getNeonArbitraryTokenAccount', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getPayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPdaLpMint', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getPoolData', values: [BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getPoolLpAmount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSwapInput', values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSwapOutput', values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTokenReserve', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'lockLiquidity', values: [BytesLike, BigNumberish, boolean, BytesLike]): string;
encodeFunctionData(functionFragment: 'lpToAmount', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapInput', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapOutput', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawLiquidity', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'CALL_SOLANA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collectFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPoolAndLockLP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConfigAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConfigData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCpmmPdaPoolId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getExtAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNeonAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNeonArbitraryTokenAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPdaLpMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoolData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoolLpAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSwapInput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSwapOutput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenReserve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lpToAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapInput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapOutput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawLiquidity', data: BytesLike): Result;
  }

  

  export interface CallRaydiumProgram extends BaseContract {
    
    connect(runner?: ContractRunner | null): CallRaydiumProgram;
    waitForDeployment(): Promise<this>;

    interface: CallRaydiumProgramInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CALL_SOLANA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addLiquidity: TypedContractMethod<
      [poolId: BytesLike, tokenA: AddressLike, tokenB: AddressLike, amountTokenA: BigNumberish, amountTokenB: BigNumberish, inputAmount: BigNumberish, baseIn: boolean, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    collectFees: TypedContractMethod<
      [poolId: BytesLike, tokenA: AddressLike, tokenB: AddressLike, lpFeeAmount: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createPool: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, mintAAmount: BigNumberish, mintBAmount: BigNumberish, startTime: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    createPoolAndLockLP: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, mintAAmount: BigNumberish, mintBAmount: BigNumberish, startTime: BigNumberish, salt: BytesLike, withMetadata: boolean, ],
      [[string, bigint, string]],
      'nonpayable'
    >
    

    
    getConfigAccount: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getConfigData: TypedContractMethod<
      [index: BigNumberish, ],
      [LibRaydiumData.ConfigDataStructOutput],
      'view'
    >
    

    
    getCpmmPdaPoolId: TypedContractMethod<
      [index: BigNumberish, tokenA: BytesLike, tokenB: BytesLike, ],
      [string],
      'view'
    >
    

    
    getExtAuthority: TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    getNeonAddress: TypedContractMethod<
      [evm_address: AddressLike, ],
      [string],
      'view'
    >
    

    
    getNeonArbitraryTokenAccount: TypedContractMethod<
      [token: AddressLike, evm_address: AddressLike, ],
      [string],
      'view'
    >
    

    
    getPayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPdaLpMint: TypedContractMethod<
      [poolId: BytesLike, ],
      [string],
      'view'
    >
    

    
    getPoolData: TypedContractMethod<
      [index: BigNumberish, tokenA: BytesLike, tokenB: BytesLike, ],
      [LibRaydiumData.PoolDataStructOutput],
      'view'
    >
    

    
    getPoolLpAmount: TypedContractMethod<
      [poolId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getSwapInput: TypedContractMethod<
      [poolId: BytesLike, configAccount: BytesLike, inputToken: BytesLike, outputToken: BytesLike, outputAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getSwapOutput: TypedContractMethod<
      [poolId: BytesLike, configAccount: BytesLike, inputToken: BytesLike, outputToken: BytesLike, sourceAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTokenReserve: TypedContractMethod<
      [poolId: BytesLike, tokenMint: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    lockLiquidity: TypedContractMethod<
      [poolId: BytesLike, lpAmount: BigNumberish, withMetadata: boolean, salt: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    lpToAmount: TypedContractMethod<
      [lp: BigNumberish, poolAmountA: BigNumberish, poolAmountB: BigNumberish, supply: BigNumberish, ],
      [[bigint, bigint]],
      'view'
    >
    

    
    swapInput: TypedContractMethod<
      [poolId: BytesLike, inputToken: AddressLike, outputToken: AddressLike, amountIn: BigNumberish, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapOutput: TypedContractMethod<
      [poolId: BytesLike, inputToken: AddressLike, outputToken: AddressLike, amountOut: BigNumberish, amountInMax: BigNumberish, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawLiquidity: TypedContractMethod<
      [poolId: BytesLike, tokenA: AddressLike, tokenB: AddressLike, lpAmount: BigNumberish, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CALL_SOLANA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [poolId: BytesLike, tokenA: AddressLike, tokenB: AddressLike, amountTokenA: BigNumberish, amountTokenB: BigNumberish, inputAmount: BigNumberish, baseIn: boolean, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'collectFees'): TypedContractMethod<
      [poolId: BytesLike, tokenA: AddressLike, tokenB: AddressLike, lpFeeAmount: BigNumberish, salt: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPool'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, mintAAmount: BigNumberish, mintBAmount: BigNumberish, startTime: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPoolAndLockLP'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, mintAAmount: BigNumberish, mintBAmount: BigNumberish, startTime: BigNumberish, salt: BytesLike, withMetadata: boolean, ],
      [[string, bigint, string]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getConfigAccount'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getConfigData'): TypedContractMethod<
      [index: BigNumberish, ],
      [LibRaydiumData.ConfigDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCpmmPdaPoolId'): TypedContractMethod<
      [index: BigNumberish, tokenA: BytesLike, tokenB: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getExtAuthority'): TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getNeonAddress'): TypedContractMethod<
      [evm_address: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getNeonArbitraryTokenAccount'): TypedContractMethod<
      [token: AddressLike, evm_address: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPdaLpMint'): TypedContractMethod<
      [poolId: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPoolData'): TypedContractMethod<
      [index: BigNumberish, tokenA: BytesLike, tokenB: BytesLike, ],
      [LibRaydiumData.PoolDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPoolLpAmount'): TypedContractMethod<
      [poolId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSwapInput'): TypedContractMethod<
      [poolId: BytesLike, configAccount: BytesLike, inputToken: BytesLike, outputToken: BytesLike, outputAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSwapOutput'): TypedContractMethod<
      [poolId: BytesLike, configAccount: BytesLike, inputToken: BytesLike, outputToken: BytesLike, sourceAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenReserve'): TypedContractMethod<
      [poolId: BytesLike, tokenMint: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockLiquidity'): TypedContractMethod<
      [poolId: BytesLike, lpAmount: BigNumberish, withMetadata: boolean, salt: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lpToAmount'): TypedContractMethod<
      [lp: BigNumberish, poolAmountA: BigNumberish, poolAmountB: BigNumberish, supply: BigNumberish, ],
      [[bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'swapInput'): TypedContractMethod<
      [poolId: BytesLike, inputToken: AddressLike, outputToken: AddressLike, amountIn: BigNumberish, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapOutput'): TypedContractMethod<
      [poolId: BytesLike, inputToken: AddressLike, outputToken: AddressLike, amountOut: BigNumberish, amountInMax: BigNumberish, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawLiquidity'): TypedContractMethod<
      [poolId: BytesLike, tokenA: AddressLike, tokenB: AddressLike, lpAmount: BigNumberish, slippage: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }