/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IERC20ForSplInterface extends Interface {
    getFunction(nameOrSignature: "tokenMint" | "transferFrom" | "transferSolana"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'tokenMint', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferSolana', values: [BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'tokenMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferSolana', data: BytesLike): Result;
  }

  

  export interface IERC20ForSpl extends BaseContract {
    
    connect(runner?: ContractRunner | null): IERC20ForSpl;
    waitForDeployment(): Promise<this>;

    interface: IERC20ForSplInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    tokenMint: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferSolana: TypedContractMethod<
      [to: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'tokenMint'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [sender: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferSolana'): TypedContractMethod<
      [to: BytesLike, amount: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }