/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface SolanaVRFInterface extends Interface {
    getFunction(nameOrSignature: "CALL_SOLANA" | "fulfilledAccountLength" | "getRandomness" | "randomnessAccountAddress" | "requestRandomness" | "vrfInstructionId" | "vrfNetworkState" | "vrfProgramId" | "vrfTreasury"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'CALL_SOLANA', values?: undefined): string;
encodeFunctionData(functionFragment: 'fulfilledAccountLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRandomness', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'randomnessAccountAddress', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'requestRandomness', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'vrfInstructionId', values?: undefined): string;
encodeFunctionData(functionFragment: 'vrfNetworkState', values?: undefined): string;
encodeFunctionData(functionFragment: 'vrfProgramId', values?: undefined): string;
encodeFunctionData(functionFragment: 'vrfTreasury', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CALL_SOLANA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fulfilledAccountLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRandomness', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'randomnessAccountAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRandomness', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vrfInstructionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vrfNetworkState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vrfProgramId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vrfTreasury', data: BytesLike): Result;
  }

  

  export interface SolanaVRF extends BaseContract {
    
    connect(runner?: ContractRunner | null): SolanaVRF;
    waitForDeployment(): Promise<this>;

    interface: SolanaVRFInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CALL_SOLANA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fulfilledAccountLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRandomness: TypedContractMethod<
      [seed: BytesLike, ],
      [[string, string, bigint]],
      'view'
    >
    

    
    randomnessAccountAddress: TypedContractMethod<
      [seed: BytesLike, ],
      [string],
      'view'
    >
    

    
    requestRandomness: TypedContractMethod<
      [seed: BytesLike, lamports: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    vrfInstructionId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vrfNetworkState: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vrfProgramId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vrfTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CALL_SOLANA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fulfilledAccountLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRandomness'): TypedContractMethod<
      [seed: BytesLike, ],
      [[string, string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'randomnessAccountAddress'): TypedContractMethod<
      [seed: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requestRandomness'): TypedContractMethod<
      [seed: BytesLike, lamports: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vrfInstructionId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vrfNetworkState'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vrfProgramId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vrfTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }