/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibSystemErrors, LibSystemErrorsInterface } from "../../../../composability/libraries/system-program/LibSystemErrors.js";

  const _abi = [
  {
    "inputs": [],
    "name": "Float64Overflow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NegativeFloat64",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SystemAccountDataQuery",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220b785a86216588c6ed732c4f5bb7c6f15c8e4722f6cbd4dd650101b5e7ac2f05964736f6c634300081c0033";

  
      type LibSystemErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibSystemErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibSystemErrors__factory extends ContractFactory {
    
      constructor(...args: LibSystemErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibSystemErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibSystemErrors__factory {
      return super.connect(runner) as LibSystemErrors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibSystemErrorsInterface {
      return new Interface(_abi) as LibSystemErrorsInterface;
    }
    
    override attach(address: string | Addressable): LibSystemErrors {
      return super.attach(address) as LibSystemErrors;
    }
  static connect(address: string, runner?: ContractRunner | null): LibSystemErrors {
      return new Contract(address, _abi, runner) as unknown as LibSystemErrors;
    }
  }

  
  