/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibSystemData, LibSystemDataInterface } from "../../../../composability/libraries/system-program/LibSystemData.js";

  const _abi = [
  {
    "inputs": [],
    "name": "ACCOUNT_STORAGE_OVERHEAD",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460175760709081601c823930815050f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c6328554a50146023575f80fd5b5f36600319011260365780608060209252f35b5f80fdfea264697066735822122078a8beff8bd5a0c91547d8a37475abd6ee91b33e530dce7eb16cbb93d31a95e564736f6c634300081c0033";

  
      type LibSystemDataConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibSystemDataConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibSystemData__factory extends ContractFactory {
    
      constructor(...args: LibSystemDataConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibSystemData & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibSystemData__factory {
      return super.connect(runner) as LibSystemData__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibSystemDataInterface {
      return new Interface(_abi) as LibSystemDataInterface;
    }
    
    override attach(address: string | Addressable): LibSystemData {
      return super.attach(address) as LibSystemData;
    }
  static connect(address: string, runner?: ContractRunner | null): LibSystemData {
      return new Contract(address, _abi, runner) as unknown as LibSystemData;
    }
  }

  
  