/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { Constants, ConstantsInterface } from "../../../composability/libraries/Constants.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "chainId",
        "type": "uint256"
      }
    ],
    "name": "InvalidChain",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220fcf248b04234528d1af17acb9f7bc468f081136abe71545d091ad7e73aa97eab64736f6c634300081c0033";

  
      type ConstantsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ConstantsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Constants__factory extends ContractFactory {
    
      constructor(...args: ConstantsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Constants & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Constants__factory {
      return super.connect(runner) as Constants__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ConstantsInterface {
      return new Interface(_abi) as ConstantsInterface;
    }
    
    override attach(address: string | Addressable): Constants {
      return super.attach(address) as Constants;
    }
  static connect(address: string, runner?: ContractRunner | null): Constants {
      return new Contract(address, _abi, runner) as unknown as Constants;
    }
  }

  
  