/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICallSolana, ICallSolanaInterface } from "../../precompiles/ICallSolana.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "space",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "lamports",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "owner",
        "type": "bytes32"
      }
    ],
    "name": "createResource",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "lamports",
        "type": "uint64"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "program_id",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "account",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "is_signer",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "is_writable",
                "type": "bool"
              }
            ],
            "internalType": "struct ICallSolana.AccountMeta[]",
            "name": "accounts",
            "type": "tuple[]"
          },
          {
            "internalType": "bytes",
            "name": "instruction_data",
            "type": "bytes"
          }
        ],
        "internalType": "struct ICallSolana.Instruction",
        "name": "instruction",
        "type": "tuple"
      }
    ],
    "name": "execute",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "lamports",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "instruction",
        "type": "bytes"
      }
    ],
    "name": "execute",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "lamports",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "instruction",
        "type": "bytes"
      }
    ],
    "name": "executeWithSeed",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "lamports",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "program_id",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "account",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "is_signer",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "is_writable",
                "type": "bool"
              }
            ],
            "internalType": "struct ICallSolana.AccountMeta[]",
            "name": "accounts",
            "type": "tuple[]"
          },
          {
            "internalType": "bytes",
            "name": "instruction_data",
            "type": "bytes"
          }
        ],
        "internalType": "struct ICallSolana.Instruction",
        "name": "instruction",
        "type": "tuple"
      }
    ],
    "name": "executeWithSeed",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      }
    ],
    "name": "getExtAuthority",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "getNeonAddress",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getPayer",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      }
    ],
    "name": "getResourceAddress",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getReturnData",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "program_id",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "seeds",
        "type": "bytes"
      }
    ],
    "name": "getSolanaPDA",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ICallSolana__factory {
    static readonly abi = _abi;
    static createInterface(): ICallSolanaInterface {
      return new Interface(_abi) as ICallSolanaInterface;
    }
    
    override attach(address: string | Addressable): ICallSolana {
      return super.attach(address) as ICallSolana;
    }
  static connect(address: string, runner?: ContractRunner | null): ICallSolana {
      return new Contract(address, _abi, runner) as unknown as ICallSolana;
    }
  }
  