/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMetaplexProgram, IMetaplexProgramInterface } from "../../precompiles/IMetaplexProgram.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "mint",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "maxSupply",
        "type": "uint64"
      }
    ],
    "name": "createMasterEdition",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_mint",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_symbol",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_uri",
        "type": "string"
      }
    ],
    "name": "createMetadata",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "mint",
        "type": "bytes32"
      }
    ],
    "name": "isInitialized",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "mint",
        "type": "bytes32"
      }
    ],
    "name": "isNFT",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "mint",
        "type": "bytes32"
      }
    ],
    "name": "name",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "mint",
        "type": "bytes32"
      }
    ],
    "name": "symbol",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "mint",
        "type": "bytes32"
      }
    ],
    "name": "uri",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IMetaplexProgram__factory {
    static readonly abi = _abi;
    static createInterface(): IMetaplexProgramInterface {
      return new Interface(_abi) as IMetaplexProgramInterface;
    }
    
    override attach(address: string | Addressable): IMetaplexProgram {
      return super.attach(address) as IMetaplexProgram;
    }
  static connect(address: string, runner?: ContractRunner | null): IMetaplexProgram {
      return new Contract(address, _abi, runner) as unknown as IMetaplexProgram;
    }
  }
  