/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INeonWithdraw, INeonWithdrawInterface } from "../../precompiles/INeonWithdraw.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "account",
        "type": "bytes32"
      }
    ],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class INeonWithdraw__factory {
    static readonly abi = _abi;
    static createInterface(): INeonWithdrawInterface {
      return new Interface(_abi) as INeonWithdrawInterface;
    }
    
    override attach(address: string | Addressable): INeonWithdraw {
      return super.attach(address) as INeonWithdraw;
    }
  static connect(address: string, runner?: ContractRunner | null): INeonWithdraw {
      return new Contract(address, _abi, runner) as unknown as INeonWithdraw;
    }
  }
  