/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ISolanaNative, ISolanaNativeInterface } from "../../precompiles/ISolanaNative.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "isSolanaUser",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "solanaAddress",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ISolanaNative__factory {
    static readonly abi = _abi;
    static createInterface(): ISolanaNativeInterface {
      return new Interface(_abi) as ISolanaNativeInterface;
    }
    
    override attach(address: string | Addressable): ISolanaNative {
      return super.attach(address) as ISolanaNative;
    }
  static connect(address: string, runner?: ContractRunner | null): ISolanaNative {
      return new Contract(address, _abi, runner) as unknown as ISolanaNative;
    }
  }
  