/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20ForSplSol from './erc20_for_spl.sol/index.js';
export type { erc20ForSplSol };
import type * as erc20ForSplFactorySol from './erc20_for_spl_factory.sol/index.js';
export type { erc20ForSplFactorySol };
import type * as v1 from './v1/index.js';
export type { v1 };