/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LibSystemData } from './LibSystemData.js';
export type { LibSystemErrors } from './LibSystemErrors.js';