/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface MetaplexInterface extends Interface {
    getFunction(nameOrSignature: "createMasterEdition" | "createMetadata" | "isInitialized" | "isNFT" | "name" | "symbol" | "uri"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createMasterEdition', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createMetadata', values: [BytesLike, string, string, string]): string;
encodeFunctionData(functionFragment: 'isInitialized', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isNFT', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'name', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'uri', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'createMasterEdition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isInitialized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
  }

  

  export interface Metaplex extends BaseContract {
    
    connect(runner?: ContractRunner | null): Metaplex;
    waitForDeployment(): Promise<this>;

    interface: MetaplexInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createMasterEdition: TypedContractMethod<
      [mint: BytesLike, maxSupply: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    createMetadata: TypedContractMethod<
      [_mint: BytesLike, _name: string, _symbol: string, _uri: string, ],
      [string],
      'nonpayable'
    >
    

    
    isInitialized: TypedContractMethod<
      [mint: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    isNFT: TypedContractMethod<
      [mint: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [mint: BytesLike, ],
      [string],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [mint: BytesLike, ],
      [string],
      'view'
    >
    

    
    uri: TypedContractMethod<
      [mint: BytesLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createMasterEdition'): TypedContractMethod<
      [mint: BytesLike, maxSupply: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createMetadata'): TypedContractMethod<
      [_mint: BytesLike, _name: string, _symbol: string, _uri: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isInitialized'): TypedContractMethod<
      [mint: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isNFT'): TypedContractMethod<
      [mint: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [mint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [mint: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [mint: BytesLike, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }