/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../common.js"
  
export declare namespace SPLToken {
      
    export type AccountStruct = {mint: BytesLike, owner: BytesLike, amount: BigNumberish, delegate: BytesLike, delegated_amount: BigNumberish, close_authority: BytesLike, state: BigNumberish}

    export type AccountStructOutput = [mint: string, owner: string, amount: bigint, delegate: string, delegated_amount: bigint, close_authority: string, state: bigint] & {mint: string, owner: string, amount: bigint, delegate: string, delegated_amount: bigint, close_authority: string, state: bigint }
  

    export type MintStruct = {supply: BigNumberish, decimals: BigNumberish, isInitialized: boolean, freezeAuthority: BytesLike, mintAuthority: BytesLike}

    export type MintStructOutput = [supply: bigint, decimals: bigint, isInitialized: boolean, freezeAuthority: string, mintAuthority: string] & {supply: bigint, decimals: bigint, isInitialized: boolean, freezeAuthority: string, mintAuthority: string }
  
    }

  export interface SPLTokenInterface extends Interface {
    getFunction(nameOrSignature: "approve" | "burn" | "closeAccount" | "findAccount" | "freeze" | "getAccount" | "getMint" | "initializeAccount(bytes32,bytes32)" | "initializeAccount(bytes32,bytes32,bytes32)" | "initializeMint(bytes32,uint8)" | "initializeMint(bytes32,uint8,bytes32,bytes32)" | "isSystemAccount" | "mintTo" | "revoke" | "thaw" | "transfer" | "transferWithSeed"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'approve', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'burn', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeAccount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'findAccount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'freeze', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getAccount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMint', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'initializeAccount(bytes32,bytes32)', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'initializeAccount(bytes32,bytes32,bytes32)', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'initializeMint(bytes32,uint8)', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'initializeMint(bytes32,uint8,bytes32,bytes32)', values: [BytesLike, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'isSystemAccount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'mintTo', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revoke', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'thaw', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'transfer', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferWithSeed', values: [BytesLike, BytesLike, BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'findAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freeze', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeAccount(bytes32,bytes32)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeAccount(bytes32,bytes32,bytes32)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeMint(bytes32,uint8)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeMint(bytes32,uint8,bytes32,bytes32)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSystemAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revoke', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'thaw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferWithSeed', data: BytesLike): Result;
  }

  

  export interface SPLToken extends BaseContract {
    
    connect(runner?: ContractRunner | null): SPLToken;
    waitForDeployment(): Promise<this>;

    interface: SPLTokenInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approve: TypedContractMethod<
      [source: BytesLike, target: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burn: TypedContractMethod<
      [mint: BytesLike, account: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closeAccount: TypedContractMethod<
      [account: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    findAccount: TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    freeze: TypedContractMethod<
      [mint: BytesLike, account: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getAccount: TypedContractMethod<
      [account: BytesLike, ],
      [SPLToken.AccountStructOutput],
      'view'
    >
    

    
    getMint: TypedContractMethod<
      [account: BytesLike, ],
      [SPLToken.MintStructOutput],
      'view'
    >
    

    
    "initializeAccount(bytes32,bytes32)": TypedContractMethod<
      [salt: BytesLike, mint: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    "initializeAccount(bytes32,bytes32,bytes32)": TypedContractMethod<
      [salt: BytesLike, mint: BytesLike, owner: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    "initializeMint(bytes32,uint8)": TypedContractMethod<
      [salt: BytesLike, decimals: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    "initializeMint(bytes32,uint8,bytes32,bytes32)": TypedContractMethod<
      [salt: BytesLike, decimals: BigNumberish, mint_authority: BytesLike, freeze_authority: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    isSystemAccount: TypedContractMethod<
      [account: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    mintTo: TypedContractMethod<
      [mint: BytesLike, account: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revoke: TypedContractMethod<
      [source: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    thaw: TypedContractMethod<
      [mint: BytesLike, account: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    transfer: TypedContractMethod<
      [source: BytesLike, target: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferWithSeed: TypedContractMethod<
      [seed: BytesLike, source: BytesLike, target: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [source: BytesLike, target: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [mint: BytesLike, account: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeAccount'): TypedContractMethod<
      [account: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'findAccount'): TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'freeze'): TypedContractMethod<
      [mint: BytesLike, account: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAccount'): TypedContractMethod<
      [account: BytesLike, ],
      [SPLToken.AccountStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMint'): TypedContractMethod<
      [account: BytesLike, ],
      [SPLToken.MintStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'initializeAccount(bytes32,bytes32)'): TypedContractMethod<
      [salt: BytesLike, mint: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeAccount(bytes32,bytes32,bytes32)'): TypedContractMethod<
      [salt: BytesLike, mint: BytesLike, owner: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeMint(bytes32,uint8)'): TypedContractMethod<
      [salt: BytesLike, decimals: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeMint(bytes32,uint8,bytes32,bytes32)'): TypedContractMethod<
      [salt: BytesLike, decimals: BigNumberish, mint_authority: BytesLike, freeze_authority: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isSystemAccount'): TypedContractMethod<
      [account: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintTo'): TypedContractMethod<
      [mint: BytesLike, account: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revoke'): TypedContractMethod<
      [source: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'thaw'): TypedContractMethod<
      [mint: BytesLike, account: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [source: BytesLike, target: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferWithSeed'): TypedContractMethod<
      [seed: BytesLike, source: BytesLike, target: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }