/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LibSPLTokenData } from './LibSPLTokenData.js';
export type { LibSPLTokenErrors } from './LibSPLTokenErrors.js';