/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface ERC20ForSplFactoryInterface extends Interface {
    getFunction(nameOrSignature: "allErc20ForSpl" | "allErc20ForSplLength" | "createErc20ForSpl" | "createErc20ForSplMintable" | "getErc20ForSpl" | "getTokenMintByAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ERC20ForSplCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'allErc20ForSpl', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'allErc20ForSplLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'createErc20ForSpl', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'createErc20ForSplMintable', values: [string, string, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getErc20ForSpl', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenMintByAddress', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'allErc20ForSpl', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allErc20ForSplLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createErc20ForSpl', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createErc20ForSplMintable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getErc20ForSpl', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenMintByAddress', data: BytesLike): Result;
  }

  
    export namespace ERC20ForSplCreatedEvent {
      export type InputTuple = [_mint: BytesLike, pair: AddressLike, arg2: BigNumberish];
      export type OutputTuple = [_mint: string, pair: string, arg2: bigint];
      export interface OutputObject {_mint: string, pair: string, arg2: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ERC20ForSplFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): ERC20ForSplFactory;
    waitForDeployment(): Promise<this>;

    interface: ERC20ForSplFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allErc20ForSpl: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    allErc20ForSplLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createErc20ForSpl: TypedContractMethod<
      [_mint: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    createErc20ForSplMintable: TypedContractMethod<
      [_name: string, _symbol: string, _decimals: BigNumberish, _mint_authority: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    getErc20ForSpl: TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >
    

    
    getTokenMintByAddress: TypedContractMethod<
      [token: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allErc20ForSpl'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allErc20ForSplLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createErc20ForSpl'): TypedContractMethod<
      [_mint: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createErc20ForSplMintable'): TypedContractMethod<
      [_name: string, _symbol: string, _decimals: BigNumberish, _mint_authority: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getErc20ForSpl'): TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenMintByAddress'): TypedContractMethod<
      [token: AddressLike, ],
      [string],
      'view'
    >;

    getEvent(key: 'ERC20ForSplCreated'): TypedContractEvent<ERC20ForSplCreatedEvent.InputTuple, ERC20ForSplCreatedEvent.OutputTuple, ERC20ForSplCreatedEvent.OutputObject>;

    filters: {
      
      'ERC20ForSplCreated(bytes32,address,uint256)': TypedContractEvent<ERC20ForSplCreatedEvent.InputTuple, ERC20ForSplCreatedEvent.OutputTuple, ERC20ForSplCreatedEvent.OutputObject>;
      ERC20ForSplCreated: TypedContractEvent<ERC20ForSplCreatedEvent.InputTuple, ERC20ForSplCreatedEvent.OutputTuple, ERC20ForSplCreatedEvent.OutputObject>;
    
    };
  }