/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockVaultInterface extends Interface {
    getFunction(nameOrSignature: "ERC20ForSPLAddress" | "deposit" | "depositToSolana"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "DepositToSolana"): EventFragment;

    encodeFunctionData(functionFragment: 'ERC20ForSPLAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositToSolana', values: [BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'ERC20ForSPLAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositToSolana', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [msgSender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [msgSender: string, amount: bigint];
      export interface OutputObject {msgSender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositToSolanaEvent {
      export type InputTuple = [msgSender: AddressLike, account: BytesLike, amount: BigNumberish];
      export type OutputTuple = [msgSender: string, account: string, amount: bigint];
      export interface OutputObject {msgSender: string, account: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockVault;
    waitForDeployment(): Promise<this>;

    interface: MockVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ERC20ForSPLAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositToSolana: TypedContractMethod<
      [amount: BigNumberish, to: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ERC20ForSPLAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositToSolana'): TypedContractMethod<
      [amount: BigNumberish, to: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'DepositToSolana'): TypedContractEvent<DepositToSolanaEvent.InputTuple, DepositToSolanaEvent.OutputTuple, DepositToSolanaEvent.OutputObject>;

    filters: {
      
      'Deposit(address,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'DepositToSolana(address,bytes32,uint64)': TypedContractEvent<DepositToSolanaEvent.InputTuple, DepositToSolanaEvent.OutputTuple, DepositToSolanaEvent.OutputObject>;
      DepositToSolana: TypedContractEvent<DepositToSolanaEvent.InputTuple, DepositToSolanaEvent.OutputTuple, DepositToSolanaEvent.OutputObject>;
    
    };
  }