/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface LibMetaplexDataInterface extends Interface {
    getFunction(nameOrSignature: "CALL_SOLANA" | "CREATE_FEE_OFFSET" | "CREATE_FEE_SCALAR" | "MAX_CREATOR_LEN" | "MAX_CREATOR_LIMIT" | "MAX_DATA_SIZE" | "MAX_METADATA_LEN" | "MAX_NAME_LENGTH" | "MAX_SYMBOL_LENGTH" | "MAX_URI_LENGTH"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'CALL_SOLANA', values?: undefined): string;
encodeFunctionData(functionFragment: 'CREATE_FEE_OFFSET', values?: undefined): string;
encodeFunctionData(functionFragment: 'CREATE_FEE_SCALAR', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_CREATOR_LEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_CREATOR_LIMIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_DATA_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_METADATA_LEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SYMBOL_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_URI_LENGTH', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CALL_SOLANA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CREATE_FEE_OFFSET', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CREATE_FEE_SCALAR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_CREATOR_LEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_CREATOR_LIMIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_DATA_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_METADATA_LEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SYMBOL_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_URI_LENGTH', data: BytesLike): Result;
  }

  

  export interface LibMetaplexData extends BaseContract {
    
    connect(runner?: ContractRunner | null): LibMetaplexData;
    waitForDeployment(): Promise<this>;

    interface: LibMetaplexDataInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CALL_SOLANA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CREATE_FEE_OFFSET: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CREATE_FEE_SCALAR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_CREATOR_LEN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_CREATOR_LIMIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_DATA_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_METADATA_LEN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SYMBOL_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_URI_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CALL_SOLANA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CREATE_FEE_OFFSET'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CREATE_FEE_SCALAR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_CREATOR_LEN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_CREATOR_LIMIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_DATA_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_METADATA_LEN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SYMBOL_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_URI_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }