/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibRaydiumData, LibRaydiumDataInterface } from "../../../../composability/libraries/raydium-program/LibRaydiumData.js";

  const _abi = [
  {
    "inputs": [],
    "name": "CALL_SOLANA",
    "outputs": [
      {
        "internalType": "contract ICallSolana",
        "name": "",
        "type": "ICallSolana"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460175760759081601c823930815050f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c62b8d849146022575f80fd5b5f366003190112603b57600660ff60981b018152602090f35b5f80fdfea2646970667358221220b66798558e8b0882ea63b2a99f7ee73d528c5100df41ca875c7b3ca8e537f70464736f6c634300081c0033";

  
      type LibRaydiumDataConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibRaydiumDataConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibRaydiumData__factory extends ContractFactory {
    
      constructor(...args: LibRaydiumDataConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibRaydiumData & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibRaydiumData__factory {
      return super.connect(runner) as LibRaydiumData__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibRaydiumDataInterface {
      return new Interface(_abi) as LibRaydiumDataInterface;
    }
    
    override attach(address: string | Addressable): LibRaydiumData {
      return super.attach(address) as LibRaydiumData;
    }
  static connect(address: string, runner?: ContractRunner | null): LibRaydiumData {
      return new Contract(address, _abi, runner) as unknown as LibRaydiumData;
    }
  }

  
  