/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibRaydiumErrors, LibRaydiumErrorsInterface } from "../../../../composability/libraries/raydium-program/LibRaydiumErrors.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "poolId",
        "type": "bytes32"
      }
    ],
    "name": "AlreadyExistingPool",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyTokenAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "IdenticalTokenAddresses",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientInputAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientOutputAmount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "configAccount",
        "type": "bytes32"
      }
    ],
    "name": "InvalidConfig",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "poolId",
        "type": "bytes32"
      }
    ],
    "name": "InvalidPool",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroSupply",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220881b8dd786f768fb0ccd627339304246b6b5f3663a62fb150b6ed4290793281a64736f6c634300081c0033";

  
      type LibRaydiumErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibRaydiumErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibRaydiumErrors__factory extends ContractFactory {
    
      constructor(...args: LibRaydiumErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibRaydiumErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibRaydiumErrors__factory {
      return super.connect(runner) as LibRaydiumErrors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibRaydiumErrorsInterface {
      return new Interface(_abi) as LibRaydiumErrorsInterface;
    }
    
    override attach(address: string | Addressable): LibRaydiumErrors {
      return super.attach(address) as LibRaydiumErrors;
    }
  static connect(address: string, runner?: ContractRunner | null): LibRaydiumErrors {
      return new Contract(address, _abi, runner) as unknown as LibRaydiumErrors;
    }
  }

  
  