/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ICallSolana {
      
    export type AccountMetaStruct = {account: BytesLike, is_signer: boolean, is_writable: boolean}

    export type AccountMetaStructOutput = [account: string, is_signer: boolean, is_writable: boolean] & {account: string, is_signer: boolean, is_writable: boolean }
  

    export type InstructionStruct = {program_id: BytesLike, accounts: ICallSolana.AccountMetaStruct[], instruction_data: BytesLike}

    export type InstructionStructOutput = [program_id: string, accounts: ICallSolana.AccountMetaStructOutput[], instruction_data: string] & {program_id: string, accounts: ICallSolana.AccountMetaStructOutput[], instruction_data: string }
  
    }

  export interface ICallSolanaInterface extends Interface {
    getFunction(nameOrSignature: "createResource" | "execute(uint64,(bytes32,(bytes32,bool,bool)[],bytes))" | "execute(uint64,bytes)" | "executeWithSeed(uint64,bytes32,bytes)" | "executeWithSeed(uint64,bytes32,(bytes32,(bytes32,bool,bool)[],bytes))" | "getExtAuthority" | "getNeonAddress" | "getPayer" | "getResourceAddress" | "getReturnData" | "getSolanaPDA"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createResource', values: [BytesLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'execute(uint64,(bytes32,(bytes32,bool,bool)[],bytes))', values: [BigNumberish, ICallSolana.InstructionStruct]): string;
encodeFunctionData(functionFragment: 'execute(uint64,bytes)', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'executeWithSeed(uint64,bytes32,bytes)', values: [BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'executeWithSeed(uint64,bytes32,(bytes32,(bytes32,bool,bool)[],bytes))', values: [BigNumberish, BytesLike, ICallSolana.InstructionStruct]): string;
encodeFunctionData(functionFragment: 'getExtAuthority', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getNeonAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'getResourceAddress', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getReturnData', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSolanaPDA', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'createResource', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute(uint64,(bytes32,(bytes32,bool,bool)[],bytes))', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute(uint64,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeWithSeed(uint64,bytes32,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeWithSeed(uint64,bytes32,(bytes32,(bytes32,bool,bool)[],bytes))', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getExtAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNeonAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getResourceAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReturnData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSolanaPDA', data: BytesLike): Result;
  }

  

  export interface ICallSolana extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICallSolana;
    waitForDeployment(): Promise<this>;

    interface: ICallSolanaInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createResource: TypedContractMethod<
      [salt: BytesLike, space: BigNumberish, lamports: BigNumberish, owner: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    "execute(uint64,(bytes32,(bytes32,bool,bool)[],bytes))": TypedContractMethod<
      [lamports: BigNumberish, instruction: ICallSolana.InstructionStruct, ],
      [string],
      'nonpayable'
    >
    

    
    "execute(uint64,bytes)": TypedContractMethod<
      [lamports: BigNumberish, instruction: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    "executeWithSeed(uint64,bytes32,bytes)": TypedContractMethod<
      [lamports: BigNumberish, salt: BytesLike, instruction: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    "executeWithSeed(uint64,bytes32,(bytes32,(bytes32,bool,bool)[],bytes))": TypedContractMethod<
      [lamports: BigNumberish, salt: BytesLike, instruction: ICallSolana.InstructionStruct, ],
      [string],
      'nonpayable'
    >
    

    
    getExtAuthority: TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    getNeonAddress: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    getPayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getResourceAddress: TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    getReturnData: TypedContractMethod<
      [],
      [[string, string]],
      'view'
    >
    

    
    getSolanaPDA: TypedContractMethod<
      [program_id: BytesLike, seeds: BytesLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createResource'): TypedContractMethod<
      [salt: BytesLike, space: BigNumberish, lamports: BigNumberish, owner: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'execute(uint64,(bytes32,(bytes32,bool,bool)[],bytes))'): TypedContractMethod<
      [lamports: BigNumberish, instruction: ICallSolana.InstructionStruct, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'execute(uint64,bytes)'): TypedContractMethod<
      [lamports: BigNumberish, instruction: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeWithSeed(uint64,bytes32,bytes)'): TypedContractMethod<
      [lamports: BigNumberish, salt: BytesLike, instruction: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeWithSeed(uint64,bytes32,(bytes32,(bytes32,bool,bool)[],bytes))'): TypedContractMethod<
      [lamports: BigNumberish, salt: BytesLike, instruction: ICallSolana.InstructionStruct, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getExtAuthority'): TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getNeonAddress'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getResourceAddress'): TypedContractMethod<
      [salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReturnData'): TypedContractMethod<
      [],
      [[string, string]],
      'view'
    >;
getFunction(nameOrSignature: 'getSolanaPDA'): TypedContractMethod<
      [program_id: BytesLike, seeds: BytesLike, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }