/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { CallSolanaValidationLib, CallSolanaValidationLibInterface } from "../../utils/CallSolanaValidationLib.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidInstruction",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSolanaAccount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSolanaAccountParameters",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSolanaProgram",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220a153276a2af9026dfcfa39484627c0cced3bf76a520b3ae4a30863274c61105764736f6c634300081c0033";

  
      type CallSolanaValidationLibConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CallSolanaValidationLibConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CallSolanaValidationLib__factory extends ContractFactory {
    
      constructor(...args: CallSolanaValidationLibConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CallSolanaValidationLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CallSolanaValidationLib__factory {
      return super.connect(runner) as CallSolanaValidationLib__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CallSolanaValidationLibInterface {
      return new Interface(_abi) as CallSolanaValidationLibInterface;
    }
    
    override attach(address: string | Addressable): CallSolanaValidationLib {
      return super.attach(address) as CallSolanaValidationLib;
    }
  static connect(address: string, runner?: ContractRunner | null): CallSolanaValidationLib {
      return new Contract(address, _abi, runner) as unknown as CallSolanaValidationLib;
    }
  }

  
  