/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibSPLTokenErrors, LibSPLTokenErrorsInterface } from "../../../../composability/libraries/spl-token-program/LibSPLTokenErrors.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "ata",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "delegatedAmount",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "claimedAmount",
        "type": "uint64"
      }
    ],
    "name": "InsufficientDelegatedAmount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenAccount",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "ownerAuthority",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "closeAuthority",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "invalidAuthority",
        "type": "bytes32"
      }
    ],
    "name": "InvalidCloseAuthority",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenMint",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "freezeAuthority",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "invalidAuthority",
        "type": "bytes32"
      }
    ],
    "name": "InvalidFreezeAuthority",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenMint",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "mintAuthority",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "invalidAuthority",
        "type": "bytes32"
      }
    ],
    "name": "InvalidMintAuthority",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenAccount",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "ownerAuthority",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "invalidAuthority",
        "type": "bytes32"
      }
    ],
    "name": "InvalidOwnerAuthority",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "ata",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "delegate",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "invalidSpender",
        "type": "bytes32"
      }
    ],
    "name": "InvalidSpender",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenAccount",
        "type": "bytes32"
      }
    ],
    "name": "InvalidTokenAccountAuthorityType",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenMint",
        "type": "bytes32"
      }
    ],
    "name": "InvalidTokenMintAuthorityType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenAccountDataQuery",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenMintDataQuery",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212208d0ca2143de49311e2953bf0ad0ba1097666a9eedb923c099c1ec3ed943dfd3f64736f6c634300081c0033";

  
      type LibSPLTokenErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibSPLTokenErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibSPLTokenErrors__factory extends ContractFactory {
    
      constructor(...args: LibSPLTokenErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibSPLTokenErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibSPLTokenErrors__factory {
      return super.connect(runner) as LibSPLTokenErrors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibSPLTokenErrorsInterface {
      return new Interface(_abi) as LibSPLTokenErrorsInterface;
    }
    
    override attach(address: string | Addressable): LibSPLTokenErrors {
      return super.attach(address) as LibSPLTokenErrors;
    }
  static connect(address: string, runner?: ContractRunner | null): LibSPLTokenErrors {
      return new Contract(address, _abi, runner) as unknown as LibSPLTokenErrors;
    }
  }

  
  