/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibSPLTokenData, LibSPLTokenDataInterface } from "../../../../composability/libraries/spl-token-program/LibSPLTokenData.js";

  const _abi = [
  {
    "inputs": [],
    "name": "CALL_SOLANA",
    "outputs": [
      {
        "internalType": "contract ICallSolana",
        "name": "",
        "type": "ICallSolana"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SPL_TOKEN_ACCOUNT_SIZE",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SPL_TOKEN_MINT_SIZE",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460175760b59081601c823930815050f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c908162b8d849146066575080635664bb3b1460515763c825a18a146038575f80fd5b5f366003190112604d57602060405160528152f35b5f80fd5b5f366003190112604d57602060405160a58152f35b5f366003190112604d57600660ff60981b018152602090f3fea26469706673582212205732ee74f2bb6a5a63ba6b62584a64e7cce80b4d7e352b7889f6b4f9471869a764736f6c634300081c0033";

  
      type LibSPLTokenDataConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibSPLTokenDataConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibSPLTokenData__factory extends ContractFactory {
    
      constructor(...args: LibSPLTokenDataConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibSPLTokenData & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibSPLTokenData__factory {
      return super.connect(runner) as LibSPLTokenData__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibSPLTokenDataInterface {
      return new Interface(_abi) as LibSPLTokenDataInterface;
    }
    
    override attach(address: string | Addressable): LibSPLTokenData {
      return super.attach(address) as LibSPLTokenData;
    }
  static connect(address: string, runner?: ContractRunner | null): LibSPLTokenData {
      return new Contract(address, _abi, runner) as unknown as LibSPLTokenData;
    }
  }

  
  