/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IERC20ForSPL, IERC20ForSPLInterface } from "../../../mocks/MockVault.sol/IERC20ForSPL.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transferFrom",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "to",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      }
    ],
    "name": "transferSolanaFrom",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IERC20ForSPL__factory {
    static readonly abi = _abi;
    static createInterface(): IERC20ForSPLInterface {
      return new Interface(_abi) as IERC20ForSPLInterface;
    }
    
    override attach(address: string | Addressable): IERC20ForSPL {
      return super.attach(address) as IERC20ForSPL;
    }
  static connect(address: string, runner?: ContractRunner | null): IERC20ForSPL {
      return new Contract(address, _abi, runner) as unknown as IERC20ForSPL;
    }
  }
  