/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MockVault, MockVaultInterface } from "../../../mocks/MockVault.sol/MockVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_ERC20ForSPLAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Deposit",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "msgSender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "account",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      }
    ],
    "name": "DepositToSolana",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "ERC20ForSPLAddress",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      },
      {
        "internalType": "bytes32",
        "name": "to",
        "type": "bytes32"
      }
    ],
    "name": "depositToSolana",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a034607357601f61034438819003918201601f19168301916001600160401b03831184841017607757808492602094604052833981010312607357516001600160a01b03811681036073576080526040516102b8908161008c8239608051818181607d0152818161017201526102050152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015610012575f80fd5b5f3560e01c9081631e1a989d146101f35750806392145b591461011d5763b6b55f251461003d575f80fd5b34610119576020366003190112610119576040516323b872dd60e01b8152336004828101919091523060248301523560448201819052906020816064815f7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03165af1801561010e576100e1575b506040519081527fe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c60203392a2005b6101029060203d602011610107575b6100fa8183610234565b81019061026a565b6100b2565b503d6100f0565b6040513d5f823e3d90fd5b5f80fd5b346101195760403660031901126101195760043567ffffffffffffffff81168091036101195760405163c1ad8e1b60e01b8152336004820152602480359082018190526044820183905291906020816064815f7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03165af1801561010e576101d6575b506040519081527f9bd2c5fb37f800222cdfdf5dbf99989d0fa310e871364582ca6ef7804e6b932360203392a3005b6101ee9060203d602011610107576100fa8183610234565b6101a7565b34610119575f366003190112610119577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b90601f8019910116810190811067ffffffffffffffff82111761025657604052565b634e487b7160e01b5f52604160045260245ffd5b9081602091031261011957518015158103610119579056fea26469706673582212209fe9a8271476fa83b84a7aeb9d3c6110c4c7294fbea239844ff7d7ca073f737a64736f6c634300081c0033";

  
      type MockVaultConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockVaultConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockVault__factory extends ContractFactory {
    
      constructor(...args: MockVaultConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_ERC20ForSPLAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_ERC20ForSPLAddress, overrides || {});
    };
    override deploy(_ERC20ForSPLAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_ERC20ForSPLAddress, overrides || {}) as Promise<MockVault & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockVault__factory {
      return super.connect(runner) as MockVault__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockVaultInterface {
      return new Interface(_abi) as MockVaultInterface;
    }
    
    override attach(address: string | Addressable): MockVault {
      return super.attach(address) as MockVault;
    }
  static connect(address: string, runner?: ContractRunner | null): MockVault {
      return new Contract(address, _abi, runner) as unknown as MockVault;
    }
  }

  
  