/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibMetaplexData, LibMetaplexDataInterface } from "../../../../composability/libraries/metaplex-program/LibMetaplexData.js";

  const _abi = [
  {
    "inputs": [],
    "name": "CALL_SOLANA",
    "outputs": [
      {
        "internalType": "contract ICallSolana",
        "name": "",
        "type": "ICallSolana"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "CREATE_FEE_OFFSET",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "CREATE_FEE_SCALAR",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_CREATOR_LEN",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_CREATOR_LIMIT",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_DATA_SIZE",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_METADATA_LEN",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_NAME_LENGTH",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_SYMBOL_LENGTH",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_URI_LENGTH",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346019576101a6908161001e823930815050f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c908162b8d849146101565750806322fce66f1461013f578063254a361b1461012857806337acf4261461011157806382ddb090146100fb57806386074985146100e6578063a8d14a47146100d0578063aab5a877146100ba578063e3d89171146100a45763f53180da14610089575f80fd5b5f3660031901126100a057602060405161025f8152f35b5f80fd5b5f3660031901126100a0576020604051600a8152f35b5f3660031901126100a057602060405160c88152f35b5f3660031901126100a057602060405160228152f35b5f3660031901126100a0576020604051818152f35b5f3660031901126100a057602060405160058152f35b5f3660031901126100a057602060405161051c8152f35b5f3660031901126100a05760206040516115408152f35b5f3660031901126100a05760206040516101af8152f35b5f3660031901126100a057600660ff60981b018152602090f3fea2646970667358221220532badc477b27ed3de222f732ea9fe35dae3cfe915f4daddc98fc20e6fb862c964736f6c634300081c0033";

  
      type LibMetaplexDataConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibMetaplexDataConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibMetaplexData__factory extends ContractFactory {
    
      constructor(...args: LibMetaplexDataConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibMetaplexData & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibMetaplexData__factory {
      return super.connect(runner) as LibMetaplexData__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibMetaplexDataInterface {
      return new Interface(_abi) as LibMetaplexDataInterface;
    }
    
    override attach(address: string | Addressable): LibMetaplexData {
      return super.attach(address) as LibMetaplexData;
    }
  static connect(address: string, runner?: ContractRunner | null): LibMetaplexData {
      return new Contract(address, _abi, runner) as unknown as LibMetaplexData;
    }
  }

  
  