/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibMetaplexErrors, LibMetaplexErrorsInterface } from "../../../../composability/libraries/metaplex-program/LibMetaplexErrors.js";

  const _abi = [
  {
    "inputs": [],
    "name": "BytesSliceOutOfBounds",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenMint",
        "type": "bytes32"
      }
    ],
    "name": "ImmutableMetadata",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTokenMetadata",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "metadataPDA",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "updateAuthority",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "invalidAuthority",
        "type": "bytes32"
      }
    ],
    "name": "InvalidUpdateAuthority",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MetadataAccountDataQuery",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "tokenMint",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "metadataPDA",
        "type": "bytes32"
      }
    ],
    "name": "MetadataAlreadyExists",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212205b0023afb36345361a388bb6b91b60cdd71be21e70a5482b13058fcd969e94f664736f6c634300081c0033";

  
      type LibMetaplexErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibMetaplexErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibMetaplexErrors__factory extends ContractFactory {
    
      constructor(...args: LibMetaplexErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibMetaplexErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibMetaplexErrors__factory {
      return super.connect(runner) as LibMetaplexErrors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibMetaplexErrorsInterface {
      return new Interface(_abi) as LibMetaplexErrorsInterface;
    }
    
    override attach(address: string | Addressable): LibMetaplexErrors {
      return super.attach(address) as LibMetaplexErrors;
    }
  static connect(address: string, runner?: ContractRunner | null): LibMetaplexErrors {
      return new Contract(address, _abi, runner) as unknown as LibMetaplexErrors;
    }
  }

  
  