/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { LibMetaplexProgram, LibMetaplexProgramInterface } from "../../../../composability/libraries/metaplex-program/LibMetaplexProgram.js";

  const _abi = [
  {
    "inputs": [],
    "name": "CALL_SOLANA",
    "outputs": [
      {
        "internalType": "contract ICallSolana",
        "name": "",
        "type": "ICallSolana"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460175760759081601c823930815050f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c62b8d849146022575f80fd5b5f366003190112603b57600660ff60981b018152602090f35b5f80fdfea2646970667358221220dddd610f365893afa5fedca45f85484e45799a152789640da0f91410ca0c9faa64736f6c634300081c0033";

  
      type LibMetaplexProgramConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibMetaplexProgramConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibMetaplexProgram__factory extends ContractFactory {
    
      constructor(...args: LibMetaplexProgramConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibMetaplexProgram & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibMetaplexProgram__factory {
      return super.connect(runner) as LibMetaplexProgram__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibMetaplexProgramInterface {
      return new Interface(_abi) as LibMetaplexProgramInterface;
    }
    
    override attach(address: string | Addressable): LibMetaplexProgram {
      return super.attach(address) as LibMetaplexProgram;
    }
  static connect(address: string, runner?: ContractRunner | null): LibMetaplexProgram {
      return new Contract(address, _abi, runner) as unknown as LibMetaplexProgram;
    }
  }

  
  